### ISSUE TITLE
Tournament Demo is not working

### ISSUE THREAD

**Issue by lrn2prgrm** [kuzzleio/demo#36]
In [kuzzle.io tournamet](http://kuzzle.io/demos-tutorials/multiplayer-game-kuzzle-tournament/_play ) after introducing the name the screen goes black and the console logs: 

Error: Unable to connect to kuzzle proxy server at "tournament.kuzzle.io"

And in [tournament.kuzzle.io](http://tournament.kuzzle.io ) after introducing the name the screen shows the name blinking forever and the console logs: 

Error: Unable to connect to kuzzle proxy server at "tournament.kuzzle.io"

**Comment by benoitvidis** [comment]
Thank you for you feeback. 

However, I cannot manage to reproduce the issue, neither on Chrome or Firefox. 
Does your browser/network connection accept websocket? When directly connecting to Kuzzle proxy on http://tournament.sfo.kuzzle.io:7513/ or http://tournament.ams.kuzzle.io:7513/, you should get the Upgrade request.

**Comment by lrn2prgrm** [comment]
The tournament doesn't seem to be aveliable in the page anymore. Closed.
